// react-app/src/App.js
import React from 'react';


class App extends React.Component {
 
  render(){
    let lang = ['Java', 'DotNet', 'Python'];
    let filtervalue = this.props.selectedvalue;
    let toggleval = this.props.toggleval == 'true';
    let newArray = filtervalue && filtervalue !== "0" ? lang.filter(item => item === filtervalue ) :lang
    return (
   <div class="card">
  <div class="card-header">
    React Application
  </div>
  <div class="card-body">
  <ul class="list-group list-group-flush">
  {
    newArray.map((value,index)=>{
      return <li class="list-group-item" key={index}>{value}</li>
    })
  }
  </ul>
  </div>
  <div class="card-body">
  <div class='row'>
  <div class="col-6">
    <button type="button" id="reactincrementer" class="btn btn-outline-secondary">Increment Counter</button>
    </div>
    <div class="col-6">
    {
      toggleval && 
      <span class="badge badge-info">Called from angular app!!!</span>
    }
            </div>
    </div>
</div>
</div>
    )
}
}

export default App;

// angular-app/src/app/app.component.ts
import { Component, OnInit, Input, OnChanges, SimpleChanges } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, OnChanges {
  @Input() selectedvalue: string;
  newArray: any[];
  filtervalue: string;
  lang: any[];
  ngOnInit() {
    this.lang = ['Java', 'DotNet', 'Python'];
    this.newArray = this.selectedvalue && this.selectedvalue !== '0' ? this.lang.filter(item => item === this.selectedvalue ) : this.lang;

  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes.selectedvalue.currentValue !== changes.selectedvalue.previousValue) {
      const curr = changes.selectedvalue.currentValue;
      this.newArray = curr && curr !== '0' ? this.lang.filter(item => item === curr ) : this.lang;
    }
  }
}

<div class="card">
  <div class="card-header">
  Angular Application
  </div>
  <div class="card-body">
  <ul class="list-group list-group-flush">
   <li *ngFor="let val of newArray"  class="list-group-item">{{val}}</li>
  </ul>
  </div>
  <div class="card-body">
  <button type="button" id="angularincrementer" class="btn btn-outline-secondary">Increment Counter</button>
  <button type="button" id="toggleme" style="float:right" class="btn btn-info">Toggle</button>
  </div>
</div>
